require("utils.bootstrap")
require("utils.settings")
require("utils.mappings")

require("lazy").setup("plugins")

require("configs.autopairs")
require("configs.tokyonight")
require("configs.cokeline")
require("configs.whichkey")
require("configs.telescope")
require("configs.lspsaga")
require("configs.treesitter")
require("configs.lsp")
require("configs.formatter")
require("configs.installer")
